// Generated by BUCKLESCRIPT VERSION 1.0.1 , PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives");
var VirtualDom = require("virtual-dom");
var Caml_array = require("bs-platform/lib/js/caml_array");

var attrs = new Object();

function render(count) {
  return VirtualDom.h("div", attrs, Caml_array.caml_make_vect(1, Pervasives.string_of_int(count)));
}

var wut = render(1);

var root_node = VirtualDom.create(wut);

document.body.appendChild(root_node);

var two = render(2);

var patches = VirtualDom.diff(wut, two);

var stuff = VirtualDom.patch(root_node, patches);

exports.attrs     = attrs;
exports.render    = render;
exports.wut       = wut;
exports.root_node = root_node;
exports.two       = two;
exports.patches   = patches;
exports.stuff     = stuff;
/* attrs Not a pure module */
